X-MDAV-Result: clean
X-MDAV-Processed: mail.nhom10.nt106, Wed, 23 Jun 2021 16:17:01 +0700
Return-path: <thi2256@nhom10.nt106>
Authentication-Results: mail.nhom10.nt106;
	auth=pass (login) smtp.auth=thi2256@nhom10.nt106
Received: from mycomputer by mail.nhom10.nt106 with ESMTPA id md5001000000001.msg; 
	Wed, 23 Jun 2021 16:17:00 +0700
X-Spam-Processed: mail.nhom10.nt106, Wed, 23 Jun 2021 16:17:00 +0700
	(not processed: message from trusted or authenticated source)
X-MDArrival-Date: Wed, 23 Jun 2021 16:17:00 +0700
X-Authenticated-Sender: thi2256@nhom10.nt106
X-Rcpt-To: son2137@nhom10.nt106
X-MDRcpt-To: son2137@nhom10.nt106
X-Return-Path: thi2256@nhom10.nt106
X-Envelope-From: thi2256@nhom10.nt106
X-MDaemon-Deliver-To: son2137@nhom10.nt106
From: <thi2256@nhom10.nt106>
To: <son2137@nhom10.nt106>
Subject: text
Date: Wed, 23 Jun 2021 16:16:56 +0700
Message-ID: <000001d76810$8357be10$8a073a30$@nhom10.nt106>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_0001_01D7684B.2FB6E430"
X-Mailer: Microsoft Outlook 16.0
Thread-Index: AddoEHXY9hpMHABAQmuLwIdcjlr8+w==
Content-Language: en-us
X-MDCFSigsAdded: nhom10.nt106

This is a multipart message in MIME format.

------=_NextPart_000_0001_01D7684B.2FB6E430
Content-Type: text/plain;
	charset="us-ascii"
Content-Transfer-Encoding: 7bit

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa


------=_NextPart_000_0001_01D7684B.2FB6E430
Content-Type: text/html;
	charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" =
xmlns:o=3D"urn:schemas-microsoft-com:office:office" =
xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" =
xmlns=3D"http://www.w3.org/TR/REC-html40"><head><META =
HTTP-EQUIV=3D"Content-Type" CONTENT=3D"text/html; =
charset=3Dus-ascii"><meta name=3DGenerator content=3D"Microsoft Word 15 =
(filtered medium)"><style><!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
span.EmailStyle17
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext=3D"edit">
<o:idmap v:ext=3D"edit" data=3D"1" />
</o:shapelayout></xml><![endif]--></head><body lang=3DEN-US =
link=3D"#0563C1" vlink=3D"#954F72" style=3D'word-wrap:break-word'><div =
class=3DWordSection1><p =
class=3DMsoNormal>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa<o:p></o:p></p></d=
iv></body></html>
------=_NextPart_000_0001_01D7684B.2FB6E430--
